services:
  - type: web
    name: lcts-backend
    runtime: node
    buildCommand: npm --prefix backend install
    startCommand: npm --prefix backend start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"