services:
  - type: web
    name: lcts-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_SSL
        value: "true"