name: Deploy to Bunny.net

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Bu satır manuel çalıştırma butonu ekler!

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Kodu Kopyala
      uses: actions/checkout@v3

    - name: Bunny.net Storage'a Yükle (FTP)
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: storage.bunnycdn.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
